#!/usr/bin/env python3
"""Regression guard: ontology.html must not drift from ald_ontology.json.

The rendered HTML is generated by visualize_ontology.py from ald_ontology.json, but
the canonical ontology build (build_ontology.py) rebuilds only the JSON/YAML — it does
NOT re-run the HTML generator. So an ontology change that rebuilds the JSON without
regenerating the HTML leaves ontology.html stale, which is exactly what happened: it
sat at 2026-07-22 and missed ~11 commits of ontology changes, including every pressure
term and adsorption_equilibrium_constant.

This check fails when any quantity_kind id in the compiled JSON is absent from the
rendered HTML, and specifically pins the pressure taxonomy. Run it after any ontology
change, or wire it into the ontology build.

  python3 check_ontology_html.py     # exit 1 on staleness
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
JSON = ROOT / "ald_ontology.json"
HTML = ROOT / "ontology.html"

PRESSURE_TERMS = ("chamber_total_pressure", "generic_pressure", "unknown_pressure_type",
                  "precursor_partial_pressure", "co_reactant_partial_pressure",
                  "carrier_gas_partial_pressure", "working_pressure", "base_pressure",
                  "delivery_line_pressure", "bubbler_pressure", "vapor_pressure")


def main():
    onto = json.loads(JSON.read_text())
    html = HTML.read_text()
    ids = [q["id"] for q in onto["quantity_kinds"]]
    missing = [q for q in ids if q not in html]
    press_missing = [t for t in PRESSURE_TERMS if t not in html]

    print(f"quantity_kinds in JSON : {len(ids)}")
    print(f"present in ontology.html: {len(ids) - len(missing)}")
    if press_missing:
        print(f"  PRESSURE TERMS MISSING: {press_missing}")
    if missing:
        print(f"\nSTALE — {len(missing)} quantity id(s) not in ontology.html:")
        for q in missing[:20]:
            print(f"  {q}")
        if len(missing) > 20:
            print(f"  ... and {len(missing) - 20} more")
        print("\nFix: python3 visualize_ontology.py   (do NOT hand-edit the HTML)")
        return 1
    print("\nontology.html is current with ald_ontology.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
